name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
      - deploy-workflow

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install emscripten
      run: |
        cd /tmp

        # https://emscripten.org/docs/getting_started/downloads.html
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
        source ./emsdk_env.sh

        emcc --version

    - name: Build clock
      run: |
        source /tmp/emsdk/emsdk_env.sh

        pushd clock/
        make
        cp index.* ../docs/
        popd

    - name: Push to gh-pages branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "deploy workflow"
        git config user.email "oshikiri@users.noreply.github.com"
        git checkout -b gh-pages
        git add docs/* --force
        git commit --message "Deploy docs/*"
        git push --force origin gh-pages
